# Generated by Django 4.2.8 on 2024-05-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_languagecv_user_users_languagecv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='languagecv',
        ),
        migrations.AddField(
            model_name='languagecv',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
