# Generated by Django 4.2.8 on 2024-05-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_languagecv_user_users_languagecv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='languagecv',
        ),
        migrations.AddField(
            model_name='languagecv',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
